name: DiscordBotManager-bukkit
version: '1.0'
main: com.wairesd.discordBotManager.bukkit.DiscordBotManagerBukkit
api-version: '1.21'
commands:
  discordbotmanager-bukkit:
    description: Discord bot plugin management
    permission: discordbotmanager.admin